name: Build

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - name: Install
        # @esbuild/linux-x64 has to be installed on the CI since its addition to package-lock.json is platform-specific.
        # This package is a sub-dependency.
        run: |
          npm i -D @esbuild/linux-x64
          npm ci

      - name: Build
        run: npm run build
