name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - name: Install
        # @esbuild/linux-x64 has to be installed on the CI since its addition to package-lock.json is platform-specific.
        # This package is a sub-dependency.
        run: |
          npm i -D @esbuild/linux-x64
          npm ci

      - name: Publish
        run: npm publish --access public

      - name: Configure AWS Credentials
        run: printf "${{ secrets.AWS_ACCESS_KEY_ID }}\n${{ secrets.AWS_SECRET_ACCESS_KEY }}\neu-north-1\njson\n" | aws configure

      - name: Build Storybook
        run: npm run build:storybook

      - name: Deploy Storybook
        run: |
          aws s3 rm --recursive s3://bucket-name
          aws s3 cp --recursive storybook-static s3://bucket-name
